path_model: "results/phase1/AT_densenet+cbam_exp/0_DenseNet201/0_DenseNet201_bestLoss_1.keras"
path_full_labels: "/media/jczars/4C22F02A22F01B22/$WinREAgent/Pollen_classification_view/BD/CPD1_Cr_Rs_400/Test/k1"  
nome: "GradCAM_class_well_phase3_pl_k1.png"
conv_layer_name: "activation_1"
img_size: 224
saved_dir: "./interpretation/grad_cam/"

path_data: "BD/CPD1_TEST_VIEW/k1/POLAR/"
images_labels:
- "calicotome/Fab.C.vilX400wF(2019)(0)D-17.png"
- "eucalyptus/Myr.E.camaX400wF(2962)(0)H-27.png" 
- "salvia/Lam.S.triX400wF(2191)(0)D-33.png"
- "thymbra/Lam.T.capX400wF(1032)(0)D-9.png"
