path_model: "results/phase1/AT_densenet+cbam_exp/0_DenseNet201/0_DenseNet201_bestLoss_1.keras"
nome: "GradCAM_class_wrong_phase3_pl_k1.png"
conv_layer_name: "activation_1"
img_size: 224
saved_dir: "./interpretation/grad_cam/"

path_data: "BD/CPD1_TEST_VIEW/k1/POLAR/"
images_labels:
- "vitis/Vit.V.viniX400wF(4978)(0)A-24.png"
- "ceratonia/Fab.C.silX400wF(481)(0)G-12.png"
- "origanum/Lam.O.micX400wF(884)(0)A-2.png"
- "satureja/Lam.S.thyX400wF(947)(0)H-4.png"
