# Número de pastas de dobras (k-folds) no dataset
k_folds: 10

normalize: False

# Diretório onde estão os relatóriios de avaliação
folder:
- 'results/phase1/AT_densenet+cbam_exp/0_DenseNet201_reports/'  
- 'results/phase1/AT_densenet+cbam_exp/1_DenseNet201_reports/' 
- 'results/phase1/AT_densenet+cbam_exp/2_DenseNet201_reports/'
- 'results/phase1/AT_densenet+cbam_exp/3_DenseNet201_reports/'
- 'results/phase1/AT_densenet+cbam_exp/4_DenseNet201_reports/'
- 'results/phase1/AT_densenet+cbam_exp/5_DenseNet201_reports/'